# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI Job

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        os: [ubuntu-22.04, windows-2022, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version:  ${{ matrix.go-version }}
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...

  release-to-github:
    needs: [ build-and-test ]
    runs-on: "ubuntu-22.04"
    if: contains(github.ref, 'release')
    steps: 
    - uses: actions/checkout@v2 
    - name: Get Release version 
      run: |
            version=$(cat ./VersionMaster.txt)
            echo "GOBUILDHELPERS_VERSION=$version"
            echo "GOBUILDHELPERS_VERSION=$version" >> $GITHUB_ENV 
    - uses: "marvinpinto/action-automatic-releases@latest"
      name: Release version ${{ env.GOBUILDHELPERS_VERSION }} on GitHub
      with:
        repo_token: "${{ secrets.WORKFLOW_TOKEN }}"
        automatic_release_tag: v${{ env.GOBUILDHELPERS_VERSION }}
        prerelease: false
        title: Release v${{ env.GOBUILDHELPERS_VERSION }} of the github.com/imker25/gobuildhelpers module


